apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v1
spec:
  replicas: 3
  selector:
    app: web-v1
  template:
    metadata:
      name: web-v1
      labels:
        app: web-v1
    spec:
      containers:
      - name: web-v1
        image: web-v1
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-v1-svc
spec:
  selector:
    app: web-v1-svc
  ports:
  - port: 80
    targetPort: 80