apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v2
spec:
  replicas: 3
  selector:
    app: web-v2
  template:
    metadata:
      name: web-v2
      labels:
        app: web-v2
    spec:
      containers:
      - name: web-v2
        image: grovince/test:v2-deploy
        ports:
        - containerPort: 80