apiVersion: v1
kind: ConfigMap
metadata: 
  name: mysql-cnf
data: 
  utf8.cnf: |
    [client]
    default-character-set = utf8
    
    [mysqld]
    skip-grant-tables
    init_connect = SET collation_connection = utf8_general_ci
    init_connect = SET NAMES utf8
    character-set-server = utf8
    collation-server = utf8_general_ci
    skip-character-set-client-handshake

    
    [mysqldump]
    default-character-set = utf8
    
    [mysql]
    default-character-set = utf8
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  create-db.sql: |
    CREATE DATABASE IF NOT EXISTS boot_board;
#skip-grant-tables