apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2  # 이름은 원하는 대로 설정할 수 있습니다.
provisioner: pd.csi.storage.gke.io
# provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard  # SSD를 원하면 pd-ssd를 사용합니다.
  #fsType: ext4  # 파일 시스템 타입, 필요에 따라 변경 가능
