apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 3
  selector:
    app: web-v1
  template:
    metadata:
      name: web-v1
      labels:
        app: web-v1
    spec:
      containers:
      - name: web-v1
        image: nginx
        ports:
        - containerPort: 80