apiVersion: v1
kind: Pod
metadata:
  name: web-pod-v2
  labels:
    app: web-pod-v2
spec:
  containers:
  - name: web-pod-v2
    image: grovince/test:v2-4
    imagePullPolicy: Always
    ports:
    - containerPort: 80