apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: grovince/test:rolling-update-v1

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer