apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce # 볼륨에 대한 읽기와 쓰기를 한 번에 하나의 노드에서만 수행
  persistentVolumeReclaimPolicy: Retain # PVC 삭제 후 PV를 보존
  storageClassName: standard
  hostPath:
    path: /var/lib/mysql
